### PR TITLE
[Dotnet] Namespace collision fix

### LINKED ISSUE #666: Name `Microsoft.Graph.Security` Collision Between Namespace and Class FQN
Issue detected in pipeline [run here](https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=65200&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=006e6f7c-8314-5e02-a3df-483f3a1f4cfa).

Error: error CS0101: The namespace 'Microsoft.Graph' already contains a definition for 'Security'

Need to refactor the generator to make it possible for the namespace and class to co-exist without raising compilation error.

Workload owner Confirmed the intentionality of the above as follows:
"
    `The microsoft.graph.security` singleton in Prod (beta & v1.0) exists for few years. It does not exists in PPE. I added it to my workload in PPE in order to mimic the same behavior as in Prod. We've been requested to move all our entities (in M365Defender workload) to a new sub namespace - `microsoft.graph.security`. We moved all our entities to the new sub namespace, but we didn't touch the security singleton in order to mimic the behavior in Prod
"

### PR DESCRIPTION
**Pull request by andrueastman**
This PR closes #666 

Changes include :-
- The introduction of a `ReservedNamespace` collection to allow disambiguation of namespaces(by appending the string "namespace") that cause collision with type names as described in #666. (Arguably it would have been simpler to rename the `Security` model or change its namespace but this would have the unintended consequence of being a breaking change in v1.0)
- Code cleanup by replacing the repeated code section below to simply call `DisambiguateTypeName()`. This enables us to close https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/391 by allowing `Task` to be renamed to `TaskObject` easily.
```cs
if (propertyType.EndsWith("Request"))
{
	propertyType = String.Concat(propertyType, "Object");
}
```
- Added tests to validate this. (updating the test metadata necessitated the update of java test models)

Notes: 

- Successful Raptor run on Staging beta - https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=65362&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=12f1170f-54f2-53f3-20dd-22fc7dff55f9
- Generation diff on V1 (no diff proving we generated the same SDK )- https://github.com/microsoftgraph/msgraph-sdk-dotnet/compare/dev...v1.0/pipelinebuild/65359
- Generation diff on beta (disambiguates Task) - https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/compare/master...beta/pipelinebuild/65359

cc @fey101 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/668)

### CODE REVIEW

**Review by fey101 — DISMISSED** [review]
Thanks for this fix.

File: src/GraphODataTemplateWriter/CodeHelpers/CSharp/TypeHelperCSharp.cs [hunk 1]
```diff
@@ -319,7 +329,8 @@ public static bool IsComplex(this string t)
         private static readonly Inflector inflector = new Inflector(CultureInfo.GetCultureInfo("en-US"));
         public static string GetNamespaceName(this OdcmNamespace namespaceObject)
         {
-            return inflector.Titleize(namespaceObject.Name).Replace(" ", "");
+            var nameSpaceName = GetReservedNameSpaces().Contains(namespaceObject.Name) ? $"{namespaceObject.Name}NameSpace" : namespaceObject.Name;
```
Comment (zengin) [inline src/GraphODataTemplateWriter/CodeHelpers/CSharp/TypeHelperCSharp.cs:332]: Given that namespace is a single word, can we use Namespace instead of NameSpace?

**Review by zengin — CHANGES_REQUESTED** [review]

File: src/GraphODataTemplateWriter/CodeHelpers/CSharp/TypeHelperCSharp.cs (hunk 1 above)
Comment (andrueastman) [reply src/GraphODataTemplateWriter/CodeHelpers/CSharp/TypeHelperCSharp.cs]: Thanks. Resolved via https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/668/commits/9c622b62caf0b3c83e46c884d4738646a40dbeb0

**Review by zengin — APPROVED** [review]
