### PR TITLE
Fix type issues in PHPDocs.

### LINKED ISSUE #521: Set correct return type in PHP Docs for types that clash with PHP keywords
GraphList is a model whose name is derived by pre-pending "Graph" to the actual EntityType `List` in the metadata in order to prevent clashing with keywords in PHP.

The phpDocs generated however still show return type as `List` instead of `GraphList` e.g.

```php
  /**
  * Sets the list
  * Provides additional details about the list.
  *
  * @param ListInfo $val The list
  *
  * @return List
  */
  public function setList($val)
  {
      $this->_propDict["list"] = $val;
      return $this;
  }
``` 
[AB#9134](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9134)

### PR DESCRIPTION
**Pull request by SilasKenneth**
## Summary
PHPDocs of some setters set the return to a wrong class in the PHPDoc. This happens mostly when the class is also an inbuilt PHP type prefixed with `Graph`.
## Generated code differences
Screenshot 2021-05-26 at 13 57 57

## Command line arguments to run these changes
N/A
## Links to issues or work items this PR addresses
Closes #521
#### Links to SDK PRs
[#493](https://github.com/microsoftgraph/msgraph-sdk-php/pull/493)
[#492](https://github.com/microsoftgraph/msgraph-sdk-php/pull/492)
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/535)

### CODE REVIEW

**Review by baywet — APPROVED** [review]

File: Templates/templates/PHP/Model/EntityType.php.tt [hunk 1]
```diff
@@ -114,7 +114,7 @@ foreach(var property in entity.Properties.Where(prop => prop.Type.GetTypeString(
     *
     * @param <#=propertyTypeReference#> $val The <#=propertyName#>
     *
-    * @return <#=entityCheckedCase#>
+    * @return <#=entityName.ToCheckedCase()#>
```
Comment (Ndiritu) [inline Templates/templates/PHP/Model/EntityType.php.tt:117]: We could consider `@return $this` here & on the other setters returning $this. More explicit that we're returning the instance of the current object (https://docs.phpdoc.org/3.0/guide/guides/types.html).

**Review by Ndiritu — CHANGES_REQUESTED** [review]
Nice work. We're missing similar changes for `GraphList` and `Beta\GraphCase` though...

File: Templates/templates/PHP/Model/EntityType.php.tt [hunk 2]
```diff
@@ -40,12 +40,12 @@ if (String.IsNullOrEmpty(entityBaseName)) {
     * The array of properties available
     * to the model
     *
-    * @var array(string => string)
```
[the remark this answers is not in the document]
Comment (Ndiritu) [reply Templates/templates/PHP/Model/EntityType.php.tt:43]: i.e. that the array is associative and contains <string, string>

**Comment by Ndiritu** [comment]
Sorry, just seen the GraphList and GraphCase changes on the PHP SDK repo. Should they also be here?

File: Templates/templates/PHP/Model/EntityType.php.tt (hunk 1 above)
Comment (SilasKenneth) [reply Templates/templates/PHP/Model/EntityType.php.tt:117]: Any reasons for the choice of `$this` over just the class name?

File: Templates/templates/PHP/Model/EntityType.php.tt (hunk 2 above)
[the remark this answers is not in the document]
Comment (SilasKenneth) [reply Templates/templates/PHP/Model/EntityType.php.tt:43]: From how we add items to the `$_propDict`, the values are not always strings but sometimes other types. Also the notation above is invalid when you run a code analysis tools against the code.

**Comment by SilasKenneth** [comment]
> Sorry, just seen the GraphList and GraphCase changes on the PHP SDK repo. Should they also be here?

Yes, the changes are in the test data PHP directory.

File: Templates/templates/PHP/Model/EntityType.php.tt (hunk 1 above)
Comment (Ndiritu) [reply Templates/templates/PHP/Model/EntityType.php.tt:117]: More specificity. Shows that the method not only returns an instance of the class but the same instance the method was called on
Helpful also if somebody overrides a class. `return $this` allows the IDE to suggest/autocomplete the inherited setters.

**Review by Ndiritu — APPROVED** [review]
